# config/koelectra.yaml

project:
  name: "koelectra-sliding-single"
  seed: 42
  output_dir: "make-model/experiments/koelectra_small_sliding_single_optuna/checkpoint-2131"

data:
  file_path: "make-model/data/interim/train_final.csv"
  method: "sliding"
  max_len: 512
  stride: 256
  val_size: 0.2
  delimiter: ","
  quotechar: '"'

predict:
  test_path: "make-model/data/raw/test.csv"
  submission_dir: "make-model/experiments/temp_submission"
  submission_file: "submission_koelectra_test.csv"

model:
  name: "monologg/koelectra-small-v3-discriminator"
  num_labels: 2

train:
  batch_size: 32
  epochs: 10
  learning_rate: 5.278509726144334e-05
  patience: 3
  weight_decay: 0.03689698583218482
  label_smoothing: 0.1
  fp16: true